# Generated by Django 5.2.15 on 2026-06-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heatmaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('camera_id', models.CharField(db_index=True, max_length=128)),
                ('coordenadas_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Telemetria_Afluencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('camera_id', models.CharField(db_index=True, max_length=128)),
                ('personas_entrantes', models.IntegerField(default=0)),
                ('personas_salientes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('camera_id', models.CharField(db_index=True, max_length=128)),
                ('risk_score', models.FloatField()),
                ('rules_triggered', models.JSONField(blank=True, default=list)),
                ('video_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['camera_id', '-timestamp'], name='alerts_api__camera__2052cd_idx'), models.Index(fields=['-risk_score'], name='alerts_api__risk_sc_fe39ad_idx')],
            },
        ),
    ]
