# Generated by Django 5.2.15 on 2026-06-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='alerts_api__camera__2052cd_idx',
            old_name='alerts_api_camera__2d9fd6_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='alerts_api__risk_sc_fe39ad_idx',
            old_name='alerts_api_risk_sc_221995_idx',
        ),
    ]
