# Generated by Django 5.2.15 on 2026-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='personas_en_cola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='tiempo_espera_promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
