# Generated by Codex on 2026-06-16

import secrets

from django.db import migrations, models
import django.db.models.deletion


def generate_api_key():
    return secrets.token_urlsafe(32)


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0002_telemetria_afluencia_personas_en_cola_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(max_length=128, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='alerts_api.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EdgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('api_key', models.CharField(default=generate_api_key, editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_nodes', to='alerts_api.store')),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('video_source', models.CharField(blank=True, default='', max_length=512)),
                ('roi_polygon', models.JSONField(blank=True, default=list)),
                ('queue_wait_threshold', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='alerts_api.edgenode')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='alerts_api.store')),
            ],
            options={
                'ordering': ['camera_id'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['store', 'camera_id'], name='alerts_api__store_i_9f5ee7_idx'),
        ),
    ]
