# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0003_multitenant_camera_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cashier_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='camera',
            name='max_allowed_wait_seconds',
            field=models.FloatField(default=120.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='queue_alert_duration_seconds',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='queue_alert_people_threshold',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='camera',
            name='queue_dwell_seconds',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='queue_roi_polygon',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='camera',
            name='service_rate_per_cashier_per_minute',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='alerta_cola_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='motivo_alerta_cola',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='presion_cola_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='tiempo_espera_estimado',
            field=models.FloatField(default=0.0),
        ),
    ]
