# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0004_queue_config_and_telemetry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgenode',
            name='control_api_base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
