# Generated by Django 5.2.15 on 2026-06-20 23:50

import alerts_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0005_edgenode_control_api_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_cameras',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='edgenode',
            name='api_key',
            field=models.CharField(default=alerts_api.models.generate_api_key, editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='edgenode',
            name='control_api_base_url',
            field=models.CharField(blank=True, default='http://host.docker.internal:8081', max_length=255),
        ),
    ]
