# Generated by Django 5.2.15 on 2026-06-21 00:12

import alerts_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0006_tenant_max_cameras_alter_edgenode_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(default=alerts_api.models.generate_api_key, max_length=128, unique=True),
        ),
    ]
