# Generated by Django 5.2.15 on 2026-06-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0007_tenant_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='counting_line',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='camera',
            name='counting_line_direction',
            field=models.CharField(blank=True, default='forward', max_length=20),
        ),
    ]
