# Generated by Django 5.2.15 on 2026-06-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0008_camera_counting_line_camera_counting_line_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='custom_zones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='telemetria_afluencia',
            name='sectores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
