# Generated by Django 5.2.15 on 2026-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0009_camera_custom_zones_telemetria_afluencia_sectores'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
