# Generated by Django 5.2.15 on 2026-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0010_securityalert_zona'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='heatmaps',
            index=models.Index(fields=['camera_id', '-timestamp'], name='alerts_api__camera__9babe8_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetria_afluencia',
            index=models.Index(fields=['camera_id', '-timestamp'], name='alerts_api__camera__e3d572_idx'),
        ),
    ]
