# Generated by Django 5.2.15 on 2026-06-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0011_heatmaps_alerts_api__camera__9babe8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('incomplete', 'Incompleta'), ('active', 'Activa'), ('past_due', 'Pago Vencido'), ('canceled', 'Cancelada')], default='active', max_length=20),
        ),
    ]
